In [1]:
# Introduction to Tesors

In [2]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [3]:
# Creating tensorswith tf.constant()
scalar=tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [4]:
# finding the number of dimensions in tensors
scalar.ndim

0

In [5]:
# Creating the vector using tf.constant()
vector=tf.constant([6,0])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 0], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
# Creating the matrix
matrix=tf.constant([[1,2,3,4,5],[8,2,3,5,7]])
matrix

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[1, 2, 3, 4, 5],
       [8, 2, 3, 5, 7]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
matrix2=tf.constant([[1.2,7.,9.],
                     [9.,2.1,7.1],
                     [4.,3.,2.]],dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1.2, 7. , 9. ],
       [9. , 2.1, 7.1],
       [4. , 3. , 2. ]], dtype=float16)>

In [10]:
 matrix2.ndim

2

In [11]:
# Creating 3 dimensional data
tensor=tf.constant([[[1,2,5,1],[1,2,3,8]],[[2,3,7,9],[0,6,22,9]],[[2,3,4,7],[8,9.,8,1]]])
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[ 1.,  2.,  5.,  1.],
        [ 1.,  2.,  3.,  8.]],

       [[ 2.,  3.,  7.,  9.],
        [ 0.,  6., 22.,  9.]],

       [[ 2.,  3.,  4.,  7.],
        [ 8.,  9.,  8.,  1.]]], dtype=float32)>

In [12]:
tensor.ndim

3

In [13]:
# Creating tensor with "tf.Variable()"

In [14]:
variable=tf.Variable([7])
variable

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([7], dtype=int32)>

In [15]:
variable.assign_add([1])

<tf.Variable 'UnreadVariable' shape=(1,) dtype=int32, numpy=array([8], dtype=int32)>

In [16]:
variable.assign_sub([2])

<tf.Variable 'UnreadVariable' shape=(1,) dtype=int32, numpy=array([6], dtype=int32)>

In [17]:
variable

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([6], dtype=int32)>

In [20]:
# Creating random tensors
random_1=tf.random.Generator.from_seed(51) # seed for reproducibility
random_1=random_1.normal(shape=(7,2))
random_1

<tf.Tensor: shape=(7, 2), dtype=float32, numpy=
array([[ 2.006022  ,  0.28288034],
       [-0.30288252, -1.443651  ],
       [ 1.0034493 ,  0.20857747],
       [ 0.35700995,  1.0648885 ],
       [ 1.2432485 , -2.2173238 ],
       [ 0.18706243,  0.6617961 ],
       [ 0.01380118, -0.24827152]], dtype=float32)>

In [25]:
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(7,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(7,2))

random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(7, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284],
        [ 0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263]], dtype=float32)>,
 <tf.Tensor: shape=(7, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284],
        [ 0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263]], dtype=float32)>,
 <tf.Tensor: shape=(7, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [27]:
# Shuffle with tensor (valuable with shuffling of data)
data=tf.constant([[1,4,5,6],
                  [6,3,7,0],
                  [7,3,9,2]],dtype=tf.int32)
data

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 4, 5, 6],
       [6, 3, 7, 0],
       [7, 3, 9, 2]], dtype=int32)>

In [35]:
shuffle=tf.random. shuffle(data)
shuffle

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[6, 3, 7, 0],
       [7, 3, 9, 2],
       [1, 4, 5, 6]], dtype=int32)>

In [36]:
tf.random.set_seed(51)    #Global level seed
s huffle=tf.random. shuffle(data,seed=51)   #Operational level seed
shuffle

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[7, 3, 9, 2],
       [6, 3, 7, 0],
       [1, 4, 5, 6]], dtype=int32)>

In [37]:
tf.ones(shape=(4,4),dtype=tf.int32)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [38]:
tf.zeros(shape=(4,4),dtype=tf.int32)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

In [39]:
tf.eye(4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [45]:
import numpy as np

array=np.arange(1,16,2,dtype=np.int32)  #arranging 1 to 16 numbers by increment of 2
tensor=tf.constant(array,shape=(2,4),dtype=tf.float16) # Converting numpy arrays as tensors
tensor

<tf.Tensor: shape=(2, 4), dtype=float16, numpy=
array([[ 1.,  3.,  5.,  7.],
       [ 9., 11., 13., 15.]], dtype=float16)>

In [46]:
tensor.ndim

2